DROP SCHEMA IF EXISTS CRITERIA;

CREATE SCHEMA CRITERIA ;

DROP IF EXISTS TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT (
  DNO int(4) NOT NULL,
  DNAME varchar(25) NOT NULL,
  DLOC varchar(25) NOT NULL,
  PRIMARY KEY (DNO)
);

DROP IF EXISTS TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE (
  EID int(4) NOT NULL AUTO_INCREMENT,
  ENAME varchar(25) NOT NULL,
  SAL double NOT NULL,
  DEPTNO int(4) DEFAULT NULL,
  PRIMARY KEY (EID),
  KEY DTOM_FK (DEPTNO),
  CONSTRAINT DEPT_FK FOREIGN KEY (DEPTNO) REFERENCES DEPARTMENT (DNO)
);


